import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen">
      <Navbar />
      <article className="container mx-auto px-6 py-16 max-w-3xl prose prose-slate" data-testid="page-terms">
        <h1 className="font-heading text-4xl font-bold mb-2 text-primary-foreground">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="space-y-6 text-slate-700 leading-relaxed">
          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">1. Agreement</h2>
            <p>By creating an account or using TaleWeaver ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service. The Service is operated by TaleWeaver.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">2. Eligibility & Children</h2>
            <p>You must be 18 years or older to create an account, place orders, or provide payment information. TaleWeaver creates books <em>for</em> children but is purchased and operated by adults. Adults submitting content about a child confirm they are the parent or legal guardian and have authority to do so.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">3. AI-Generated Content</h2>
            <p>Story text and illustrations are generated by artificial intelligence based on the prompts and answers you provide. AI output may contain inaccuracies, unexpected details, or stylistic variations. You are responsible for reviewing each book before ordering a printed copy. Output is generated on demand and may differ between runs.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">4. Your Content & License</h2>
            <p>You retain ownership of the personal stories, photos, and answers you submit. You grant TaleWeaver a limited license to process this content to generate your book and improve the Service. You may not upload content that is illegal, infringes on someone else's rights, contains personal information about other minors without consent, or is otherwise prohibited.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">5. Subscriptions & Billing</h2>
            <p>Subscriptions renew automatically each month at the listed price until cancelled. You can cancel any time from the Billing Portal — cancellation takes effect at the end of the current billing period. Unused free-book credits do not roll over.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">6. Acceptable Use</h2>
            <p>Do not use the Service to generate content that is sexual, violent, hateful, harassing, defamatory, or that depicts real children in inappropriate contexts. We may suspend accounts that violate these rules.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">7. Disclaimer & Liability</h2>
            <p>The Service is provided "as is" without warranty of any kind. To the maximum extent permitted by law, TaleWeaver is not liable for indirect, incidental, or consequential damages. Our total liability for any claim is limited to the amount you paid in the last 12 months.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">8. Changes</h2>
            <p>We may update these Terms from time to time. Material changes will be communicated via email or in-app notice. Continued use of the Service after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="font-heading text-2xl font-bold mt-8 mb-3 text-primary-foreground">9. Contact</h2>
            <p>Questions? Email <a href="mailto:support@taleweaver.com" className="text-primary underline">support@taleweaver.com</a>.</p>
          </section>
        </div>
      </article>
      <Footer />
    </div>
  );
}
